// Server-rendered HTML for the admin dashboard. Plain template strings, no view engine.
const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const NAV = [['overview', '📊 Overview'], ['roster', '🗂️ Roster'], ['staff', '🧑‍💼 Staff'], ['applications', '📝 Applications'], ['verification', '🪪 Verification'], ['activity', '📈 Activity'], ['breaks', '🌴 Breaks'], ['settings', '⚙️ Settings']];

const CSS = `
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
:root{--bg:#0b0f14;--panel:rgba(255,255,255,.035);--panel2:rgba(255,255,255,.06);--line:rgba(255,255,255,.08);--line2:rgba(255,255,255,.14);--fg:#eef2f6;--muted:#8a94a6;--accent:#2dd4bf;--accent2:#6d8cff;--green:#3ddc84;--red:#ff5c6c;--yellow:#ffc857;--purple:#b48cff;--r:14px;--shadow:0 10px 30px rgba(0,0,0,.35)}
*{box-sizing:border-box}html{scroll-behavior:smooth}
body{margin:0;background:var(--bg);color:var(--fg);font:15px/1.55 Inter,system-ui,-apple-system,Segoe UI,Roboto,sans-serif;-webkit-font-smoothing:antialiased;min-height:100vh;background-image:radial-gradient(900px 500px at -10% -10%,rgba(45,212,191,.16),transparent 60%),radial-gradient(700px 400px at 110% 10%,rgba(109,140,255,.16),transparent 60%),radial-gradient(600px 400px at 50% 120%,rgba(180,140,255,.08),transparent 60%);background-attachment:fixed}
a{color:#8fd8ff;text-decoration:none}a:hover{text-decoration:underline}
::selection{background:rgba(45,212,191,.35)}
.top{display:flex;align-items:center;gap:14px;padding:12px 20px;background:rgba(11,15,20,.7);backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px);border-bottom:1px solid var(--line);position:sticky;top:0;z-index:20}
.top .brand{font-weight:800;font-size:17px;color:var(--fg);letter-spacing:-.2px;display:flex;align-items:center;gap:8px}.top .brand:hover{text-decoration:none}
.top .sp{flex:1}.top img{width:30px;height:30px;border-radius:50%;border:2px solid var(--line2)}
.top .user{display:flex;align-items:center;gap:10px;color:var(--muted);font-size:14px;background:var(--panel);border:1px solid var(--line);padding:4px 12px 4px 4px;border-radius:999px}.top .user a{color:var(--muted)}.top .user a:hover{color:var(--fg)}
.wrap{display:flex;min-height:calc(100vh - 57px)}
.side{width:236px;padding:16px 12px;flex-shrink:0;position:sticky;top:57px;height:calc(100vh - 57px);overflow:auto}
.side a{display:flex;align-items:center;gap:10px;padding:10px 12px;border-radius:10px;color:var(--muted);margin-bottom:3px;font-weight:500;font-size:14.5px;transition:background .15s,color .15s,transform .15s}
.side a:hover{background:var(--panel2);color:var(--fg);text-decoration:none;transform:translateX(2px)}
.side a.on{background:linear-gradient(135deg,rgba(45,212,191,.28),rgba(109,140,255,.2));color:#fff;box-shadow:inset 0 0 0 1px rgba(45,212,191,.45)}
.side .g{padding:6px 12px 14px;border-bottom:1px solid var(--line);margin-bottom:10px;font-size:13px;color:var(--muted)}.side .g b{display:block;color:var(--fg);font-size:14.5px;margin-bottom:2px}.side .g img{width:22px;height:22px;border-radius:7px;vertical-align:middle;margin-right:6px}
main{flex:1;padding:28px 32px 60px;max-width:1120px;min-width:0}
h1{font-size:26px;margin:0 0 4px;font-weight:800;letter-spacing:-.4px}h2{font-size:15px;margin:26px 0 10px;font-weight:700;text-transform:uppercase;letter-spacing:.6px;color:var(--muted)}h3{margin:0 0 8px;font-size:16px}.sub{color:var(--muted);margin:0 0 22px;font-size:14.5px}
.card{background:var(--panel);border:1px solid var(--line);border-radius:var(--r);padding:20px;margin-bottom:16px;backdrop-filter:blur(6px);box-shadow:var(--shadow);transition:border-color .15s}.card:hover{border-color:var(--line2)}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:14px}
.stat{background:var(--panel);border:1px solid var(--line);border-radius:var(--r);padding:18px 18px 14px;position:relative;overflow:hidden}.stat:before{content:'';position:absolute;inset:0 0 auto 0;height:3px;background:linear-gradient(90deg,var(--accent),var(--accent2),var(--purple))}
.stat b{display:block;font-size:30px;font-weight:800;letter-spacing:-.6px;background:linear-gradient(135deg,#fff,#bfeee8);-webkit-background-clip:text;background-clip:text;color:transparent}.stat span{color:var(--muted);font-size:12.5px;font-weight:500;text-transform:uppercase;letter-spacing:.5px}
label{display:block;margin:14px 0 6px;color:var(--muted);font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:.5px}
input[type=text],input[type=number],input[type=url],select,textarea{width:100%;background:rgba(0,0,0,.35);color:var(--fg);border:1px solid var(--line2);border-radius:10px;padding:10px 12px;font:inherit;transition:border-color .15s,box-shadow .15s;outline:none}
input:focus,select:focus,textarea:focus{border-color:var(--accent);box-shadow:0 0 0 3px rgba(45,212,191,.22)}
select{appearance:none;-webkit-appearance:none;background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='8'%3E%3Cpath d='M1 1l5 5 5-5' stroke='%238a94a6' stroke-width='2' fill='none'/%3E%3C/svg%3E");background-repeat:no-repeat;background-position:right 12px center;padding-right:32px}
select[multiple]{background-image:none;min-height:140px;padding:6px}select[multiple] option{padding:6px 8px;border-radius:6px}select[multiple] option:checked{background:linear-gradient(0deg,var(--accent),var(--accent));color:#012}
textarea{min-height:90px;resize:vertical}
.row{display:grid;grid-template-columns:1fr 1fr;gap:16px}.row3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:16px}
.tog{display:flex;align-items:center;gap:14px;padding:12px 0;border-bottom:1px solid var(--line)}.tog:last-child{border:0}.tog small{color:var(--muted);display:block;font-size:13px;font-weight:400}
.tog input[type=checkbox]{appearance:none;-webkit-appearance:none;width:44px;height:26px;border-radius:999px;background:rgba(255,255,255,.12);border:1px solid var(--line2);position:relative;cursor:pointer;flex-shrink:0;transition:background .2s,border-color .2s;margin:0}
.tog input[type=checkbox]:before{content:'';position:absolute;top:3px;left:3px;width:18px;height:18px;border-radius:50%;background:#fff;transition:transform .2s;box-shadow:0 1px 3px rgba(0,0,0,.4)}
.tog input[type=checkbox]:checked{background:linear-gradient(135deg,var(--accent),var(--accent2));border-color:transparent}.tog input[type=checkbox]:checked:before{transform:translateX(18px)}
button,.btn{background:linear-gradient(135deg,var(--accent),var(--accent2));color:#04141a;border:0;border-radius:10px;padding:10px 18px;font:inherit;font-weight:700;cursor:pointer;display:inline-block;transition:transform .12s,box-shadow .15s,filter .15s;box-shadow:0 6px 18px rgba(45,212,191,.25)}
button:hover,.btn:hover{transform:translateY(-1px);filter:brightness(1.08);text-decoration:none}button:active{transform:translateY(0)}
button.sec,.btn.sec{background:var(--panel2);border:1px solid var(--line2);box-shadow:none;color:var(--fg)}button.danger,.btn.danger{background:linear-gradient(135deg,#ff5c6c,#ff3d7f);box-shadow:0 6px 18px rgba(255,92,108,.25);color:#fff}button.ok{background:linear-gradient(135deg,#3ddc84,#22c1a3)}
button.sm,.btn.sm{padding:6px 11px;font-size:13px;border-radius:8px}
.ok{background:rgba(61,220,132,.1);border:1px solid rgba(61,220,132,.4);color:#9be0b0;padding:12px 16px;border-radius:12px;margin-bottom:16px;font-weight:500}
.err{background:rgba(255,92,108,.1);border:1px solid rgba(255,92,108,.45);padding:12px 16px;border-radius:12px;margin-bottom:16px;font-weight:500}
table{width:100%;border-collapse:separate;border-spacing:0}th,td{padding:10px 12px;border-bottom:1px solid var(--line);text-align:left;font-size:14px;vertical-align:middle}th{color:var(--muted);font-weight:600;font-size:11.5px;text-transform:uppercase;letter-spacing:.5px}
tr:last-child td{border-bottom:0}tbody tr:hover td{background:rgba(255,255,255,.025)}
.tag{display:inline-block;padding:3px 10px;border-radius:999px;font-size:12px;font-weight:600;background:var(--panel2);border:1px solid var(--line);white-space:nowrap}
.tag.interview,.tag.open{background:rgba(180,140,255,.15);color:#d2b3ff;border-color:rgba(180,140,255,.35)}.chart{width:100%;height:auto;display:block}.chart text{font:11px Inter,sans-serif;fill:var(--muted)}.chart .bar:hover{filter:brightness(1.25)}.leg{display:flex;gap:14px;flex-wrap:wrap;font-size:13px;color:var(--muted);margin-top:8px}.leg i{display:inline-block;width:10px;height:10px;border-radius:3px;margin-right:5px;vertical-align:middle}
.tag.active{background:rgba(61,220,132,.15);color:#8fe0ad;border-color:rgba(61,220,132,.35)}.tag.loa{background:rgba(180,140,255,.15);color:#d2b3ff;border-color:rgba(180,140,255,.35)}.tag.resigned{color:var(--muted)}.tag.pending{background:rgba(109,140,255,.15);color:#b8c6ff;border-color:rgba(109,140,255,.35)}.tag.accepted,.tag.approved,.tag.verified{background:rgba(61,220,132,.15);color:#8fe0ad;border-color:rgba(61,220,132,.35)}.tag.denied{background:rgba(255,92,108,.15);color:#ff9aa5;border-color:rgba(255,92,108,.35)}.tag.strike{background:rgba(255,200,87,.15);color:#ffd27a;border-color:rgba(255,200,87,.35)}
.inline{display:inline}.inline button{margin-left:4px}.actions{display:flex;gap:6px;flex-wrap:wrap;align-items:center}
.gl{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:14px}.gl a{display:flex;align-items:center;gap:14px;background:var(--panel);border:1px solid var(--line);border-radius:var(--r);padding:16px;color:var(--fg);transition:transform .15s,border-color .15s,box-shadow .15s}.gl a:hover{border-color:var(--accent);text-decoration:none;transform:translateY(-2px);box-shadow:var(--shadow)}.gl img,.gl .ph{width:48px;height:48px;border-radius:14px;background:linear-gradient(135deg,var(--accent),var(--accent2));display:flex;align-items:center;justify-content:center;font-weight:800;font-size:18px;color:#04141a;flex-shrink:0}.gl small{display:block;color:var(--muted)}
.center{max-width:560px;margin:80px auto;text-align:center;padding:0 16px}.center img{width:104px;height:104px;border-radius:28px;margin-bottom:16px;box-shadow:0 20px 50px rgba(45,212,191,.3)}
.hero{display:flex;flex-direction:column;align-items:center;gap:10px}.hero h1{font-size:34px}.hero .btn{padding:14px 28px;font-size:16px;border-radius:12px;margin-top:8px}
.feat{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px;margin-top:34px;text-align:left}.feat div{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:12px 14px;font-size:13.5px;color:var(--muted)}.feat b{display:block;color:var(--fg);font-size:14px;margin-bottom:2px}
code{background:rgba(0,0,0,.35);border:1px solid var(--line);padding:2px 7px;border-radius:6px;font-size:13px}
.dept{border:1px solid var(--line);border-radius:12px;padding:14px 16px;margin-bottom:14px;background:rgba(0,0,0,.15)}.dept h3{display:flex;align-items:center;gap:10px}.dept h3 .sp{flex:1}
.lvl{display:grid;grid-template-columns:28px 1.1fr .7fr 1fr 1fr 56px auto;gap:8px;align-items:center;padding:8px 0;border-bottom:1px solid var(--line)}.lvl:last-child{border:0}.lvl .n{color:var(--muted);font-size:12px;font-weight:700}
.feed div{padding:7px 0;border-bottom:1px solid var(--line);font-size:14px}.feed div:last-child{border:0}.feed small{color:var(--muted);margin-right:8px}
.qa{padding:8px 0;border-bottom:1px solid var(--line)}.qa:last-child{border:0}.qa b{display:block;color:var(--muted);font-size:12.5px;text-transform:uppercase;letter-spacing:.4px}.qa p{margin:2px 0 0;white-space:pre-wrap}
details summary{cursor:pointer;font-weight:600;padding:6px 0}
.av{width:32px;height:32px;border-radius:50%;vertical-align:middle;margin-right:8px;background:var(--panel2)}
.mnav{display:none;gap:6px;overflow-x:auto;padding:10px 14px;background:rgba(11,15,20,.7);backdrop-filter:blur(12px);border-bottom:1px solid var(--line);position:sticky;top:57px;z-index:15;scrollbar-width:none}.mnav::-webkit-scrollbar{display:none}.mnav a{white-space:nowrap;padding:7px 12px;border-radius:999px;color:var(--muted);background:var(--panel2);border:1px solid var(--line);font-size:13.5px;font-weight:500}.mnav a.on{color:#04141a;background:linear-gradient(135deg,var(--accent),var(--accent2));border-color:transparent}
@media(max-width:860px){.row,.row3{grid-template-columns:1fr}.side{display:none}main{padding:18px 16px 60px}.mnav{display:flex!important}.top .user span.name{display:none}h1{font-size:22px}.lvl{grid-template-columns:24px 1fr 1fr;grid-auto-rows:auto}.lvl .hide{display:none}table{display:block;overflow-x:auto}.msgs{grid-template-columns:1fr}}
@media(prefers-reduced-motion:reduce){*{transition:none!important}}
`;

function layout({ title, session, team, page, body }) {
  const nav = team ? NAV.map(([k, l]) => `<a class="${page === k ? 'on' : ''}" href="/dashboard/${team.id}${k === 'overview' ? '' : '/' + k}">${l}</a>`).join('') : '';
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} — StaffHub</title><style>${CSS}</style></head><body>
<div class="top"><a class="brand" href="/dashboard">🧑‍💼 StaffHub</a><span class="sp"></span>${session ? `<span class="user">${session.user.avatar ? `<img src="${esc(session.user.avatar)}" alt="">` : ''}<span class="name">${esc(session.user.username)}</span><a href="/auth/logout" title="Log out">⏻</a></span>` : ''}</div>
${team ? `<div class="mnav">${nav}</div>` : ''}
<div class="wrap">${team ? `<nav class="side"><div class="g"><b>${team.mainIcon ? `<img src="${esc(team.mainIcon)}" alt="">` : ''}${esc(team.mainName)}</b>staff server: ${esc(team.staffName)}</div>${nav}<a href="/dashboard" style="margin-top:12px">← All teams</a></nav>` : ''}<main>${body}</main></div></body></html>`;
}

const flash = (q) => (q?.ok ? `<div class="ok">✅ ${esc(q.ok)}</div>` : q?.err ? `<div class="err">❌ ${esc(q.err)}</div>` : '');
const csrf = (s) => `<input type="hidden" name="_csrf" value="${esc(s.csrf)}">`;
const when = (iso) => (iso ? new Date(iso).toLocaleString('en-GB', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'UTC' }) + ' UTC' : '—');
const ago = (iso) => { const s = (Date.now() - new Date(iso)) / 1000; if (s < 60) return 'just now'; if (s < 3600) return `${Math.floor(s / 60)}m ago`; if (s < 86400) return `${Math.floor(s / 3600)}h ago`; return `${Math.floor(s / 86400)}d ago`; };
const until = (iso) => { const s = (new Date(iso) - Date.now()) / 1000; if (s <= 0) return 'ending'; if (s < 3600) return `${Math.ceil(s / 60)}m left`; if (s < 86400) return `${Math.ceil(s / 3600)}h left`; return `${Math.ceil(s / 86400)}d left`; };
const sel = (name, items, current, none = '— none —', label = (i) => i.name) => `<select name="${name}"><option value="">${none}</option>${items.map((i) => `<option value="${i.id}" ${i.id === current ? 'selected' : ''}>${esc(label(i))}</option>`).join('')}</select>`;
const chanSel = (name, channels, current) => sel(name, channels, current, '— disabled —', (c) => `# ${c.name}`);
const roleSel = (name, roles, current) => sel(name, roles, current, '— none —', (r) => `@ ${r.name}`);
const multi = (name, items, current, label = (i) => `@ ${i.name}`) => `<select name="${name}" multiple>${items.map((i) => `<option value="${i.id}" ${current.includes(i.id) ? 'selected' : ''}>${esc(label(i))}</option>`).join('')}</select><small style="color:var(--muted)">Ctrl/Cmd-click to select several</small>`;
const check = (name, on, label, hint) => `<div class="tog"><input type="checkbox" id="${name}" name="${name}" ${on ? 'checked' : ''}><label for="${name}" style="margin:0;text-transform:none;font-size:15px;color:var(--fg);font-weight:500">${label}${hint ? `<small>${hint}</small>` : ''}</label></div>`;
const statusTag = (m) => `<span class="tag ${m.status}">${m.status === 'loa' ? '🌴 on break' : m.status}</span>`;
const posSel = (name, t, current) => `<select name="${name}">${t.departments.map((d) => `<optgroup label="${esc(d.name)}">${d.levels.map((l) => `<option value="${l.id}" ${l.id === current ? 'selected' : ''}>${esc(l.name)}</option>`).join('')}</optgroup>`).join('')}</select>`;
const userCell = (m) => `${m.avatar ? `<img class="av" src="${esc(m.avatar)}" alt="">` : '<span class="av" style="display:inline-block"></span>'}<b>${esc(m.name || m.tag)}</b><br><small style="color:var(--muted);margin-left:40px">${esc(m.tag)} · <code>${m.userId}</code></small>`;
const btnForm = (session, action, label, cls = 'sec', extra = '', confirm = '') => `<form method="post" class="inline" ${confirm ? `onsubmit="return confirm('${esc(confirm)}')"` : ''}>${csrf(session)}<input type="hidden" name="action" value="${action}">${extra}<button class="sm ${cls}">${label}</button></form>`;

module.exports = {
  esc, layout,

  landing: ({ botName, avatar }) => layout({ title: 'Welcome', body: `<div class="center hero">${avatar ? `<img src="${esc(avatar)}" alt="">` : ''}<h1>${esc(botName)}</h1><p class="sub">Staff applications, verification, roster, promotions, strikes and breaks — kept in sync between your main server and your staff server.</p><a class="btn" href="/auth/login">Login with Discord</a><p class="sub" style="margin-top:18px;font-size:13px">Administrators only. <a href="/status">Bot status</a></p>
<div class="feat"><div><b>📝 Applications</b>Custom questions, Accept/Deny, invite by DM</div><div><b>✅ Verification</b>Position role + nickname in both servers</div><div><b>🗂️ Roster</b>Departments and ranks, auto-updated</div><div><b>⬆️ Promotions</b>Roles swap automatically</div><div><b>⚠️ Strikes</b>Limit with alert / demote / remove</div><div><b>🌴 Breaks</b>Requests, approvals, LOA role, auto-return</div></div></div>` }),

  error: (msg, session) => layout({ title: 'Error', session, body: `<div class="center"><h1>Something went wrong</h1><div class="err">${esc(msg)}</div><a class="btn sec" href="/dashboard">Back</a></div>` }),

  status: ({ session, ready, guilds, uptime, ping, memoryMb, storage, errors, teams, staff }) => layout({ title: 'Status', session, body: `<h1>Bot status</h1><p class="sub">Public page — no login needed.</p>
<div class="grid"><div class="stat"><b style="color:${ready ? 'var(--green)' : 'var(--red)'}">${ready ? 'Online' : 'Offline'}</b><span>Discord</span></div><div class="stat"><b>${guilds}</b><span>Servers</span></div><div class="stat"><b>${teams}</b><span>Linked teams</span></div><div class="stat"><b>${staff}</b><span>Staff on rosters</span></div><div class="stat"><b>${Math.floor(uptime / 86400)}d ${Math.floor((uptime % 86400) / 3600)}h ${Math.floor((uptime % 3600) / 60)}m</b><span>Uptime</span></div><div class="stat"><b>${ping ?? '–'} ms</b><span>Ping</span></div><div class="stat"><b>${memoryMb} MB</b><span>Memory</span></div><div class="stat"><b style="font-size:16px">${esc(storage)}</b><span>Storage</span></div></div>
<h2>Recent errors (${errors.length})</h2><div class="card">${errors.length ? errors.slice(0, 20).map((e) => `<div style="padding:6px 0;border-bottom:1px solid var(--line)"><small style="color:var(--muted)">${esc(e.at)}</small><br><code style="white-space:pre-wrap">${esc(e.text)}</code></div>`).join('') : '<p class="sub" style="margin:0">No errors since the last restart. 🎉</p>'}</div>` }),

  teams: ({ session, teams, unlinked, invite }) => layout({ title: 'Your teams', session, body: `<h1>Your teams</h1><p class="sub">Linked main ↔ staff server pairs where you are an Administrator.</p>
${teams.length ? `<div class="gl">${teams.map((t) => `<a href="/dashboard/${t.id}">${t.mainIcon ? `<img src="${esc(t.mainIcon)}" alt="">` : `<span class="ph">${esc(t.mainName[0] || '?')}</span>`}<span><b>${esc(t.mainName)}</b><small>staff: ${esc(t.staffName)} · ${t.staffCount} staff${t.pending ? ` · <span style="color:var(--yellow)">${t.pending} pending</span>` : ''}</small></span></a>`).join('')}</div>` : '<div class="card">No linked teams yet.</div>'}
<h2>Not linked yet</h2><div class="card"><p class="sub">Servers where you are an Administrator but StaffHub is not linked. In the <b>main</b> server run <code>/link setup staff_server:&lt;staff server ID&gt;</code> (the bot must be in both servers).</p>
${unlinked.length ? `<table><tr><th>Server</th><th></th></tr>${unlinked.map((g) => `<tr><td>${g.icon ? `<img class="av" src="${esc(g.icon)}" alt="">` : ''}${esc(g.name)}</td><td style="text-align:right">${g.inBot ? '<span class="tag active">bot present</span>' : `<a class="btn sm sec" href="${esc(invite)}&guild_id=${g.id}" target="_blank">Invite bot</a>`}</td></tr>`).join('')}</table>` : '<p class="sub" style="margin:0">None.</p>'}</div>` }),

  overview: ({ session, team, page, stats, q, activity, deptStats }) => layout({ title: 'Overview', session, team, page, body: `<h1>Overview</h1><p class="sub">${esc(team.mainName)} ↔ ${esc(team.staffName)}</p>${flash(q)}
<div class="grid"><div class="stat"><b>${stats.staff}</b><span>Active staff</span></div><div class="stat"><b>${stats.loa}</b><span>On break</span></div><div class="stat"><b>${stats.pendingApps}</b><span>Pending applications</span></div><div class="stat"><b>${stats.pendingVerify}</b><span>Proof to verify</span></div><div class="stat"><b>${stats.interviews}</b><span>Open interviews</span></div><div class="stat"><b>${stats.pendingBreaks}</b><span>Break requests</span></div><div class="stat"><b>${stats.strikes30}</b><span>Strikes (30 days)</span></div><div class="stat"><b>${stats.departments}</b><span>Departments</span></div></div>
${stats.setupIssues.length ? `<h2>Setup checklist</h2><div class="card">${stats.setupIssues.map((s) => `<div style="padding:6px 0">⚠️ ${s}</div>`).join('')}</div>` : ''}
<div class="row"><div><h2>Departments</h2><div class="card">${deptStats.length ? `<table><tr><th>Department</th><th>Positions</th><th>Staff</th></tr>${deptStats.map((d) => `<tr><td>${esc(d.emoji)} <b>${esc(d.name)}</b></td><td>${d.levels}</td><td>${d.count}</td></tr>`).join('')}</table>` : '<p class="sub" style="margin:0">No departments yet — create them on the <a href="/dashboard/' + team.id + '/roster">Roster</a> page.</p>'}</div></div>
<div><h2>Recent activity</h2><div class="card feed">${activity.length ? activity.slice(0, 15).map((a) => `<div><small>${ago(a.at)}</small>${esc(a.text)}</div>`).join('') : '<p class="sub" style="margin:0">Nothing yet.</p>'}</div></div></div>` }),

  roster: ({ session, team, t, page, q, mainRoles, staffRoles, counts, rosterChannelName }) => layout({ title: 'Roster', session, team, page, body: `<h1>Roster</h1><p class="sub">Departments and their positions, <b>lowest rank first</b>. Each position has one role in the main server and one in the staff server — verify/promote/demote swap them automatically. The <b>nickname tag</b> is the short text used in nicknames (<code>${esc(t.nicknameFormat)}</code>), e.g. <code>Mod</code> instead of <code>Moderator</code>; empty = position name.</p>${flash(q)}
<div class="card" style="display:flex;gap:12px;align-items:center;flex-wrap:wrap"><span style="flex:1">📌 Live roster message: ${t.channels.roster ? `posted in <code>#${esc(rosterChannelName || t.channels.roster)}</code>, updates automatically` : 'no roster channel set — pick one in <a href="/dashboard/' + t.id + '/settings">Settings</a>'}</span>${btnForm(session, 'roster.post', '🔄 Post / refresh now', 'sec')}</div>
${t.departments.map((d, di) => `<div class="dept"><h3><form method="post" class="inline" style="display:flex;gap:8px;align-items:center;flex:1">${csrf(session)}<input type="hidden" name="action" value="dept.edit"><input type="hidden" name="dept" value="${d.id}"><input type="text" name="emoji" value="${esc(d.emoji)}" placeholder="emoji" style="width:64px"><input type="text" name="name" value="${esc(d.name)}" style="max-width:260px" required><button class="sm sec">Rename</button></form><span class="tag">${counts[d.id] || 0} staff</span>
<span class="actions">${di > 0 ? btnForm(session, 'dept.move', '↑', 'sec', `<input type="hidden" name="dept" value="${d.id}"><input type="hidden" name="dir" value="up">`) : ''}${di < t.departments.length - 1 ? btnForm(session, 'dept.move', '↓', 'sec', `<input type="hidden" name="dept" value="${d.id}"><input type="hidden" name="dir" value="down">`) : ''}${btnForm(session, 'dept.delete', 'Delete', 'danger', `<input type="hidden" name="dept" value="${d.id}">`, `Delete department "${d.name}"? Staff in it will become unassigned.`)}</span></h3>
<div class="lvl" style="border-bottom:1px solid var(--line2)"><span class="n">#</span><span class="n">POSITION</span><span class="n hide">NICKNAME TAG</span><span class="n hide">MAIN SERVER ROLE</span><span class="n hide">STAFF SERVER ROLE</span><span class="n hide">STAFF</span><span></span></div>
${d.levels.map((l, li) => `<form method="post" class="lvl">${csrf(session)}<input type="hidden" name="action" value="level.edit"><input type="hidden" name="dept" value="${d.id}"><input type="hidden" name="level" value="${l.id}"><span class="n">${li + 1}</span><input type="text" name="name" value="${esc(l.name)}" required><input type="text" name="nick" value="${esc(l.nick || '')}" placeholder="${esc(l.name.slice(0, 12))}" maxlength="12" title="Short tag used in [Tag | Name] nicknames">${roleSel('roleMain', mainRoles, l.roleMain)}${roleSel('roleStaff', staffRoles, l.roleStaff)}<span class="hide">${counts[l.id] || 0}</span><span class="actions"><button class="sm">Save</button>${li > 0 ? `<button class="sm sec" name="move" value="down" title="Lower rank">↑</button>` : ''}${li < d.levels.length - 1 ? `<button class="sm sec" name="move" value="up" title="Higher rank">↓</button>` : ''}<button class="sm danger" name="del" value="1" onclick="return confirm('Delete position ${esc(l.name)}?')">✕</button></span></form>`).join('') || '<p class="sub" style="margin:8px 0">No positions yet.</p>'}
<form method="post" class="lvl" style="border-top:1px solid var(--line);margin-top:6px;padding-top:12px">${csrf(session)}<input type="hidden" name="action" value="level.add"><input type="hidden" name="dept" value="${d.id}"><span class="n">+</span><input type="text" name="name" placeholder="New position (e.g. Senior Mod)" required><input type="text" name="nick" placeholder="Tag (e.g. Sr Mod)" maxlength="12">${roleSel('roleMain', mainRoles, null)}${roleSel('roleStaff', staffRoles, null)}<span class="hide"></span><button class="sm">Add</button></form></div>`).join('')}
<h2>New department</h2><div class="card"><form method="post" style="display:flex;gap:10px;flex-wrap:wrap;align-items:end">${csrf(session)}<input type="hidden" name="action" value="dept.add"><div style="width:90px"><label>Emoji</label><input type="text" name="emoji" placeholder="🛡️"></div><div style="flex:1;min-width:200px"><label>Name</label><input type="text" name="name" placeholder="Moderation" required></div><button>Create department</button></form></div>
<p class="sub">Tip: the bot's role must be <b>above</b> every position role in both servers, with Manage Roles and Manage Nicknames.</p>` }),

  staff: ({ session, team, t, page, q, members, filter }) => layout({ title: 'Staff', session, team, page, body: `<h1>Staff</h1><p class="sub">${members.length} shown. Click a name for the full record.</p>${flash(q)}
<form method="get" style="display:flex;gap:10px;margin-bottom:16px;flex-wrap:wrap"><input type="text" name="q" placeholder="Search name / tag / ID" value="${esc(filter.q)}" style="max-width:260px"><select name="status" style="max-width:180px"><option value="active" ${filter.status === 'active' ? 'selected' : ''}>Active + on break</option><option value="loa" ${filter.status === 'loa' ? 'selected' : ''}>On break only</option><option value="resigned" ${filter.status === 'resigned' ? 'selected' : ''}>Resigned</option><option value="all" ${filter.status === 'all' ? 'selected' : ''}>Everyone</option></select><button class="sec">Filter</button></form>
<div class="card" style="padding:0 6px"><table><tr><th>Member</th><th>Department</th><th>Position</th><th>Status</th><th>Strikes</th><th>Joined</th><th>Last active</th></tr>${members.map((m) => `<tr><td><a href="/dashboard/${t.id}/staff/${m.userId}" style="color:inherit">${userCell(m)}</a></td><td>${esc(m.deptName)}</td><td><b>${esc(m.posName)}</b><br><small style="color:var(--muted)"><code>${esc(m.nick || '')}</code></small></td><td>${statusTag(m)}</td><td>${m.activeStrikes ? `<span class="tag strike">${m.activeStrikes}/${t.strikeLimit}</span>` : '0'}</td><td><small>${when(m.joinedAt)}</small></td><td><small>${m.lastSeen ? ago(m.lastSeen) : '—'}</small></td></tr>`).join('') || '<tr><td colspan="7" class="sub" style="padding:20px">Nobody matches.</td></tr>'}</table></div>
<h2>Staff announcement</h2><div class="card"><p class="sub">Posted in the announcements channel and (optionally) DMed to every staff member — or just one department.</p><form method="post" action="/dashboard/${t.id}/staff">${csrf(session)}<input type="hidden" name="action" value="announce"><div class="row"><div><label>Title</label><input type="text" name="title" maxlength="80" placeholder="Staff meeting Sunday"></div><div><label>Department (optional)</label><select name="dept"><option value="">All staff</option>${t.departments.map((d) => `<option value="${d.id}">${esc(d.name)}</option>`).join('')}</select></div></div><label>Message</label><textarea name="message" required maxlength="1800"></textarea>${check('dm', true, 'Also DM everyone')}<button style="margin-top:10px">Send announcement</button></form></div>
<h2>Add staff manually</h2><div class="card"><p class="sub">Skips the application — for existing staff you are importing. The user must be in the staff server.</p><form method="post" action="/dashboard/${t.id}/staff" style="display:grid;grid-template-columns:1fr 1fr auto;gap:10px;align-items:end">${csrf(session)}<input type="hidden" name="action" value="add"><div><label>User ID</label><input type="text" name="userId" placeholder="123456789012345678" required pattern="\\d{15,22}"></div><div><label>Position</label>${posSel('level', t)}</div><button ${t.departments.some((d) => d.levels.length) ? '' : 'disabled'}>Verify &amp; add</button></form></div>` }),

  member: ({ session, team, t, page, q, m, user, sync }) => layout({ title: m.tag, session, team, page, body: `<a href="/dashboard/${t.id}/staff">← Staff</a><h1 style="margin-top:8px">${user?.avatar ? `<img class="av" style="width:44px;height:44px" src="${esc(user.avatar)}" alt="">` : ''}${esc(m.name || m.tag)} ${statusTag(m)}</h1><p class="sub">${esc(m.tag)} · <code>${m.userId}</code> · ${m.status === 'resigned' ? `was ${esc(m.posFull)}` : `<b>${esc(m.posFull)}</b>`} · joined staff ${when(m.joinedAt)}${m.loa ? ` · back ${when(m.loa.until)} (${until(m.loa.until)})` : ''}</p>${flash(q)}
${sync ? `<div class="card" style="padding:12px 16px;font-size:14px">Presence: main server ${sync.main ? '✅' : '❌ not in server'} · staff server ${sync.staff ? '✅' : '❌ not in server'}</div>` : ''}
<div class="row"><div>
<h2>Position</h2><div class="card">${m.status === 'resigned' ? `<p class="sub" style="margin:0 0 10px">Resigned ${when(m.resignedAt)}.</p><form method="post">${csrf(session)}<input type="hidden" name="action" value="add"><input type="hidden" name="userId" value="${m.userId}"><label>Re-add as</label>${posSel('level', t)}<button style="margin-top:10px">Re-verify &amp; add back</button></form>` : `<form method="post">${csrf(session)}<input type="hidden" name="action" value="setpos"><label>Department / position</label>${posSel('level', t, m.levelId)}<label>Reason (optional)</label><input type="text" name="reason" maxlength="300"><div class="actions" style="margin-top:12px"><button>Move</button>${btnForm(session, 'promote', '⬆️ Promote', 'sec')}${btnForm(session, 'demote', '⬇️ Demote', 'sec')}${btnForm(session, 'sync', '🔄 Re-sync roles', 'sec')}</div></form>`}</div>
<h2>Break</h2><div class="card">${m.status === 'loa' ? `<p style="margin:0 0 10px">🌴 On break until <b>${when(m.loa.until)}</b> — ${esc(m.loa.reason)}</p>${btnForm(session, 'endloa', 'End break now', 'sec')}` : m.status === 'active' ? `<form method="post" class="row" style="align-items:end">${csrf(session)}<input type="hidden" name="action" value="loa"><div><label>Duration</label><input type="text" name="duration" placeholder="3d, 1w, 12h" required></div><div><label>Reason</label><input type="text" name="reason" required maxlength="300"></div><button>Give LOA</button></form>` : '<p class="sub" style="margin:0">Not on the roster.</p>'}</div>
${m.status !== 'resigned' ? `<h2>Remove</h2><div class="card"><form method="post" onsubmit="return confirm('Remove ${esc(m.tag)} from the staff team?')">${csrf(session)}<input type="hidden" name="action" value="remove"><label>Reason (sent by DM)</label><input type="text" name="reason" maxlength="300"><button class="danger" style="margin-top:10px">Remove from staff</button></form></div>` : ''}
</div><div>
<h2>Strikes (${m.activeStrikes}/${t.strikeLimit} active${t.strikeExpiryDays ? `, expire after ${t.strikeExpiryDays}d` : ''})</h2><div class="card">${m.strikes.length ? `<table>${m.strikes.map((s) => { const active = !t.strikeExpiryDays || Date.now() - new Date(s.at) < t.strikeExpiryDays * 86400e3; return `<tr><td><b>#${s.id}</b></td><td>${esc(s.reason)}<br><small style="color:var(--muted)">${when(s.at)}${s.byTag ? ` · by ${esc(s.byTag)}` : ''} · ${active ? '<span class="tag strike">active</span>' : '<span class="tag resigned">expired</span>'}</small></td><td style="text-align:right">${btnForm(session, 'unstrike', '✕', 'sec', `<input type="hidden" name="strike" value="${s.id}">`)}</td></tr>`; }).join('')}</table>` : '<p class="sub" style="margin:0 0 10px">No strikes. 🎉</p>'}
${m.status !== 'resigned' ? `<form method="post" style="display:flex;gap:8px;margin-top:10px">${csrf(session)}<input type="hidden" name="action" value="strike"><input type="text" name="reason" placeholder="Reason for a new strike" required maxlength="500"><button class="danger">Strike</button></form>` : ''}</div>
<h2>Notes</h2><div class="card"><form method="post">${csrf(session)}<input type="hidden" name="action" value="note"><textarea name="notes" maxlength="1000" placeholder="Private notes about this staff member">${esc(m.notes || '')}</textarea><button class="sec" style="margin-top:8px">Save notes</button></form></div>
<h2>History</h2><div class="card feed">${m.history.length ? m.history.slice(0, 40).map((h) => `<div><small>${when(h.at)}</small>${esc(h.text)}${h.byTag ? ` <small>— ${esc(h.byTag)}</small>` : ''}</div>`).join('') : '<p class="sub" style="margin:0">—</p>'}</div>
${m.applicationId && t.applications[m.applicationId] ? `<h2>Application</h2><div class="card">${t.applications[m.applicationId].answers.map((qa) => `<div class="qa"><b>${esc(qa.q)}</b><p>${esc(qa.a || '—')}</p></div>`).join('')}</div>` : ''}
${m.proofUrl ? `<h2>Verification proof</h2><div class="card"><a href="${esc(m.proofUrl)}" target="_blank"><img src="${esc(m.proofUrl)}" alt="proof" style="max-width:100%;border-radius:10px"></a></div>` : ''}
</div></div>` }),

  applications: ({ session, team, t, page, q, pending, history, blacklist, inProgress }) => layout({ title: 'Applications', session, team, page, body: `<h1>Applications</h1><p class="sub">Members run <code>/apply</code> in the main server and answer the questions in their DMs. <b>Accept</b> sends the staff-server invite · <b>Interview</b> opens a private channel in the main server · <b>Deny</b> DMs the reason.</p>${flash(q)}
<h2>Pending (${pending.length})${inProgress ? ` <small style="font-weight:400;text-transform:none;letter-spacing:0">· ${inProgress} being filled in right now</small>` : ''}</h2>${pending.length ? pending.map((a) => `<div class="card"><div style="display:flex;gap:12px;align-items:center;flex-wrap:wrap"><div style="flex:1">${a.avatar ? `<img class="av" src="${esc(a.avatar)}" alt="">` : ''}<b>${esc(a.tag)}</b> <code>${a.userId}</code> <small style="color:var(--muted)">· #${a.id} · ${ago(a.at)}${a.prior ? ` · <span style="color:var(--yellow)">${a.prior} earlier application(s)</span>` : ''}${a.inStaff ? ' · <span class="tag active">in staff server</span>' : ''}${!a.inMain ? ' · <span class="tag denied">left the main server</span>' : ''}${a.status === 'interview' ? ` · <span class="tag interview">🎤 interview open</span>` : ''}</small></div><div class="actions">${btnForm(session, 'accept', '✅ Accept', 'ok', `<input type="hidden" name="app" value="${a.id}">`)}${a.status === 'interview' ? btnForm(session, 'closeinterview', '🔒 Close interview', 'sec', `<input type="hidden" name="app" value="${a.id}">`) : btnForm(session, 'interview', '🎤 Interview', 'sec', `<input type="hidden" name="app" value="${a.id}">`)}<form method="post" class="inline" style="display:flex;gap:6px">${csrf(session)}<input type="hidden" name="action" value="deny"><input type="hidden" name="app" value="${a.id}"><input type="text" name="reason" placeholder="Reason (optional)" style="width:190px;padding:6px 10px"><button class="sm danger">❌ Deny</button></form></div></div><div style="margin-top:10px">${a.answers.map((qa, i) => `<div class="qa"><b>${i + 1}. ${esc(qa.q)}</b><p>${esc(qa.a || '—')}</p></div>`).join('')}</div></div>`).join('') : '<div class="card"><p class="sub" style="margin:0">No pending applications.</p></div>'}
<div class="row"><div><h2>Questions (${t.questions.length})</h2><div class="card"><form method="post">${csrf(session)}<input type="hidden" name="action" value="questions"><p class="sub" style="margin:0 0 6px">Asked one by one in the applicant's DMs — as many as you like. One question per line; start a line with <code>*</code> to make it optional.</p><textarea name="questions" style="min-height:220px;font-family:inherit">${esc(t.questions.map((qq) => `${qq.required ? '' : '* '}${qq.label}`).join('\n'))}</textarea><button style="margin-top:12px">Save questions</button></form></div>
<h2>Options</h2><div class="card"><form method="post">${csrf(session)}<input type="hidden" name="action" value="options">${check('applicationsOpen', t.applicationsOpen, 'Applications open', 'When off, /apply shows the message below')}<label>Message when closed</label><input type="text" name="closedMessage" value="${esc(t.closedMessage)}" maxlength="500"><label>Cooldown after a denial (days, 0 = none)</label><input type="number" name="applyCooldownDays" min="0" max="365" value="${t.applyCooldownDays}"><button class="sec" style="margin-top:10px">Save options</button></form></div>
<h2>Blacklist (${blacklist.length})</h2><div class="card"><p class="sub">Blacklisted users can never apply or be verified. Adding a current staff member removes them from the team.</p>${blacklist.length ? `<table>${blacklist.map((b) => `<tr><td><b>${esc(b.tag || '')}</b> <code>${b.userId}</code><br><small style="color:var(--muted)">${esc(b.reason || 'no reason')} · ${when(b.at)}</small></td><td style="text-align:right">${btnForm(session, 'blacklist.remove', 'Remove', 'sec', `<input type="hidden" name="userId" value="${b.userId}">`)}</td></tr>`).join('')}</table>` : ''}<form method="post" style="display:grid;grid-template-columns:1fr 1fr auto;gap:8px;align-items:end;margin-top:10px">${csrf(session)}<input type="hidden" name="action" value="blacklist.add"><div><label>User ID</label><input type="text" name="userId" required pattern="\\d{15,22}"></div><div><label>Reason</label><input type="text" name="reason" maxlength="300"></div><button class="danger">Blacklist</button></form></div>
<h2>Invite</h2><div class="card"><form method="post">${csrf(session)}<input type="hidden" name="action" value="invite"><label>Staff-server invite sent to accepted applicants</label><input type="url" name="inviteUrl" value="${esc(t.inviteUrl || '')}" placeholder="https://discord.gg/… (empty = auto 1-use invite)"><button class="sec" style="margin-top:10px">Save</button></form></div></div>
<div><h2>History</h2><div class="card" style="padding:0 6px"><table><tr><th>#</th><th>Applicant</th><th>Status</th><th>When</th></tr>${history.slice(0, 40).map((a) => `<tr><td>${a.id}</td><td><details><summary>${esc(a.tag)}</summary>${a.answers.map((qa, i) => `<div class="qa"><b>${i + 1}. ${esc(qa.q)}</b><p>${esc(qa.a || '—')}</p></div>`).join('')}${a.reason ? `<p><b>Reason:</b> ${esc(a.reason)}</p>` : ''}${t.interviews[a.id] ? `<p><small style="color:var(--muted)">🎤 interviewed ${when(t.interviews[a.id].at)}</small></p>` : ''}</details></td><td><span class="tag ${a.status}">${a.status}</span></td><td><small>${when(a.reviewedAt || a.at)}</small></td></tr>`).join('') || '<tr><td colspan="4" class="sub" style="padding:16px">No reviewed applications yet.</td></tr>'}</table></div></div></div>` }),

  verification: ({ session, team, t, page, q, pending, history }) => layout({ title: 'Verification', session, team, page, body: `<h1>Verification</h1><p class="sub">Accepted applicants post their proof in the proof channel (or use <code>/proof</code>). Approve with a position — roles, nickname, guide post and announcement happen automatically. Managers can do the same from the verification channel in Discord.</p>${flash(q)}
<h2>Waiting for approval (${pending.length})</h2>${pending.length ? pending.map((v) => `<div class="card"><div class="row" style="grid-template-columns:260px 1fr;align-items:start"><div>${v.proofUrl ? `<a href="${esc(v.proofUrl)}" target="_blank"><img src="${esc(v.proofUrl)}" alt="proof" style="width:100%;border-radius:10px;border:1px solid var(--line)"></a>` : '<p class="sub">No image</p>'}</div><div><b style="font-size:16px">${esc(v.tag)}</b> <code>${v.userId}</code> <small style="color:var(--muted)">· #${v.id} · ${ago(v.at)}${v.inStaff ? ' · <span class="tag active">in staff server</span>' : ' · <span class="tag denied">left the staff server</span>'}</small>${v.note ? `<p style="margin:8px 0"><b>Note:</b> ${esc(v.note)}</p>` : ''}${v.app ? `<details style="margin:8px 0"><summary>Application #${v.app.id} (${v.app.status})</summary>${v.app.answers.map((qa) => `<div class="qa"><b>${esc(qa.q)}</b><p>${esc(qa.a || '—')}</p></div>`).join('')}</details>` : '<p class="sub" style="margin:8px 0">No application on file.</p>'}
<form method="post" style="display:grid;grid-template-columns:1fr auto;gap:8px;align-items:end;margin-top:8px">${csrf(session)}<input type="hidden" name="action" value="approve"><input type="hidden" name="req" value="${v.id}"><div><label>Approve as</label>${posSel('level', t)}</div><button class="ok">✅ Approve</button></form>
<form method="post" style="display:flex;gap:8px;margin-top:8px">${csrf(session)}<input type="hidden" name="action" value="deny"><input type="hidden" name="req" value="${v.id}"><input type="text" name="reason" placeholder="Reason (optional, sent by DM)"><button class="danger">❌ Deny</button></form></div></div></div>`).join('') : '<div class="card"><p class="sub" style="margin:0">Nothing waiting. 🎉</p></div>'}
<h2>History</h2><div class="card" style="padding:0 6px"><table><tr><th>#</th><th>User</th><th>Status</th><th>Position</th><th>Proof</th><th>When</th></tr>${history.slice(0, 40).map((v) => `<tr><td>${v.id}</td><td>${esc(v.tag)}</td><td><span class="tag ${v.status}">${v.status}</span></td><td>${esc(v.posFull)}${v.reason ? `<br><small style="color:var(--muted)">${esc(v.reason)}</small>` : ''}</td><td>${v.proofUrl ? `<a href="${esc(v.proofUrl)}" target="_blank">image</a>` : '—'}</td><td><small>${when(v.reviewedAt || v.at)}</small></td></tr>`).join('') || '<tr><td colspan="6" class="sub" style="padding:16px">—</td></tr>'}</table></div>` }),

  activity: ({ session, team, t, page, q, days, series, leaderboard, inactive }) => {
    const W = 920, H = 240, padL = 36, padB = 26, padT = 10, innerW = W - padL - 10, innerH = H - padT - padB;
    const totals = series.map((d) => d.msgs + d.mod + d.interviews + d.apps + d.verifs);
    const max = Math.max(5, ...totals);
    const bw = innerW / series.length;
    const cols = { msgs: '#2dd4bf', mod: '#6d8cff', reviews: '#b48cff' };
    const bars = series.map((d, i) => {
      const x = padL + i * bw + 1;
      const parts = [['msgs', d.msgs], ['mod', d.mod], ['reviews', d.interviews + d.apps + d.verifs]];
      let y = padT + innerH;
      const rects = parts.map(([k, v]) => { const h = (v / max) * innerH; y -= h; return v ? `<rect class="bar" x="${x.toFixed(1)}" y="${y.toFixed(1)}" width="${Math.max(1, bw - 2).toFixed(1)}" height="${h.toFixed(1)}" rx="2" fill="${cols[k]}"><title>${d.day}: ${d.msgs} messages, ${d.mod} mod actions, ${d.interviews + d.apps + d.verifs} reviews</title></rect>` : ''; }).join('');
      const label = series.length <= 31 ? (i % Math.ceil(series.length / 10) === 0 ? `<text x="${(x + bw / 2).toFixed(1)}" y="${H - 8}" text-anchor="middle">${d.day.slice(5)}</text>` : '') : (i % 10 === 0 ? `<text x="${(x + bw / 2).toFixed(1)}" y="${H - 8}" text-anchor="middle">${d.day.slice(5)}</text>` : '');
      return rects + label;
    }).join('');
    const grid = [0, 0.5, 1].map((f) => `<line x1="${padL}" x2="${W - 10}" y1="${(padT + innerH - f * innerH).toFixed(1)}" y2="${(padT + innerH - f * innerH).toFixed(1)}" stroke="rgba(255,255,255,.08)"/><text x="${padL - 6}" y="${(padT + innerH - f * innerH + 4).toFixed(1)}" text-anchor="end">${Math.round(f * max)}</text>`).join('');
    const sum = (k) => series.reduce((n, d) => n + d[k], 0);
    return layout({ title: 'Activity', session, team, page, body: `<h1>Activity</h1><p class="sub">Messages by staff in the staff server, moderation actions in the main server (from the audit log), interviews closed, applications and verifications reviewed.</p>${flash(q)}
<form method="get" style="display:flex;gap:8px;align-items:center;margin-bottom:14px"><label style="margin:0">Period</label><select name="days" style="max-width:140px" onchange="this.form.submit()">${[7, 14, 30, 60, 90].map((d) => `<option value="${d}" ${d === days ? 'selected' : ''}>${d} days</option>`).join('')}</select>${btnForm(session, 'report', '📊 Post weekly report now', 'sec')}</form>
<div class="grid"><div class="stat"><b>${sum('msgs').toLocaleString()}</b><span>Messages</span></div><div class="stat"><b>${sum('mod').toLocaleString()}</b><span>Mod actions</span></div><div class="stat"><b>${sum('interviews')}</b><span>Interviews</span></div><div class="stat"><b>${sum('apps') + sum('verifs')}</b><span>Reviews</span></div><div class="stat"><b>${inactive.length}</b><span>Inactive ${t.report.inactiveDays}+ days</span></div></div>
<h2>Last ${days} days</h2><div class="card"><svg class="chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="Staff activity per day">${grid}${bars}</svg><div class="leg"><span><i style="background:${cols.msgs}"></i>Messages</span><span><i style="background:${cols.mod}"></i>Mod actions</span><span><i style="background:${cols.reviews}"></i>Interviews &amp; reviews</span></div></div>
<div class="row"><div><h2>Leaderboard</h2><div class="card" style="padding:0 6px"><table><tr><th>#</th><th>Member</th><th>Score</th><th>Msgs</th><th>Mod</th><th>Reviews</th></tr>${leaderboard.slice(0, 25).map((x, i) => `<tr><td>${i + 1}</td><td><a href="/dashboard/${t.id}/staff/${x.m.userId}" style="color:inherit">${userCell(x.m)}</a></td><td><b>${x.total}</b></td><td>${x.msgs}</td><td>${x.mod}</td><td>${x.interviews + x.apps + x.verifs}</td></tr>`).join('') || '<tr><td colspan="6" class="sub" style="padding:16px">No staff yet.</td></tr>'}</table></div><p class="sub">Score = messages + 3×mod actions + 5×interviews + 2×application reviews + 3×verifications.</p></div>
<div><h2>Inactive (${inactive.length})</h2><div class="card" style="padding:0 6px"><table><tr><th>Member</th><th>Position</th><th>Last active</th></tr>${inactive.map((m) => `<tr><td><a href="/dashboard/${t.id}/staff/${m.userId}" style="color:inherit">${userCell(m)}</a></td><td>${esc(m.posFull)}</td><td><small>${m.lastSeen ? when(m.lastSeen) : 'never'}</small></td></tr>`).join('') || '<tr><td colspan="3" class="sub" style="padding:16px">Everyone has been active. 🎉</td></tr>'}</table></div><p class="sub">The weekly report lists these people. Change the threshold in Settings.</p></div></div>` });
  },

  breaks: ({ session, team, t, page, q, onBreak, requests, past }) => layout({ title: 'Breaks', session, team, page, body: `<h1>Breaks</h1><p class="sub">Leave of absence — the LOA role is given in both servers and removed automatically when the break ends.</p>${flash(q)}
<h2>Requests waiting (${requests.length})</h2><div class="card" style="padding:0 6px"><table><tr><th>#</th><th>Staff</th><th>Duration</th><th>Reason</th><th>Asked</th><th></th></tr>${requests.map((r) => `<tr><td>${r.id}</td><td>${userCell(r.m)}</td><td>${esc(r.duration)}</td><td>${esc(r.reason)}</td><td><small>${ago(r.at)}</small></td><td><span class="actions">${btnForm(session, 'approve', '✅ Approve', 'ok', `<input type="hidden" name="req" value="${r.id}">`)}${btnForm(session, 'denyreq', '❌ Deny', 'danger', `<input type="hidden" name="req" value="${r.id}">`)}</span></td></tr>`).join('') || '<tr><td colspan="6" class="sub" style="padding:16px">No pending requests.</td></tr>'}</table></div>
<h2>On break now (${onBreak.length})</h2><div class="card" style="padding:0 6px"><table><tr><th>Staff</th><th>Position</th><th>Reason</th><th>Back</th><th></th></tr>${onBreak.map((m) => `<tr><td>${userCell(m)}</td><td>${esc(m.posFull)}</td><td>${esc(m.loa.reason)}</td><td>${when(m.loa.until)}<br><small style="color:var(--muted)">${until(m.loa.until)}</small></td><td>${btnForm(session, 'end', 'End now', 'sec', `<input type="hidden" name="userId" value="${m.userId}">`)}</td></tr>`).join('') || '<tr><td colspan="5" class="sub" style="padding:16px">Nobody is away. 🎉</td></tr>'}</table></div>
<h2>Give a break</h2><div class="card"><form method="post" class="row3" style="align-items:end">${csrf(session)}<input type="hidden" name="action" value="give"><div><label>Staff member</label><select name="userId">${t.departments.length ? Object.values(t.members).filter((m) => m.status === 'active').map((m) => `<option value="${m.userId}">${esc(m.name || m.tag)}</option>`).join('') : ''}</select></div><div><label>Duration</label><input type="text" name="duration" placeholder="3d, 1w, 12h" required></div><div><label>Reason</label><input type="text" name="reason" required maxlength="300"></div><button>Give LOA</button></form></div>
<h2>Past requests</h2><div class="card" style="padding:0 6px"><table><tr><th>#</th><th>Staff</th><th>Duration</th><th>Status</th><th>When</th></tr>${past.slice(0, 30).map((r) => `<tr><td>${r.id}</td><td>${esc(r.tag)}</td><td>${esc(r.duration)}</td><td><span class="tag ${r.status}">${r.status}</span></td><td><small>${when(r.at)}</small></td></tr>`).join('') || '<tr><td colspan="5" class="sub" style="padding:16px">—</td></tr>'}</table></div>` }),

  settings: ({ session, team, t, page, q, staffChannels, mainChannels, mainCategories, mainRoles, staffRoles }) => layout({ title: 'Settings', session, team, page, body: `<h1>Settings</h1><p class="sub">Channels live in the staff server unless stated otherwise. Everything the bot posts is configurable here.</p>${flash(q)}
<form method="post">${csrf(session)}<input type="hidden" name="action" value="save">
<h2>Channels (staff server)</h2><div class="card"><p class="sub" style="margin:0 0 4px">Anything left disabled falls back to the <b>general log</b>. Each one gets its own buttons so managers can work from Discord.</p><div class="row">
<div><label>📝 Applications — Accept / Deny buttons</label>${chanSel('ch_applications', staffChannels, t.channels.applications)}</div>
<div><label>📸 Proof — accepted applicants post their proof here</label>${chanSel('ch_proof', staffChannels, t.channels.proof)}</div>
<div><label>🪪 Verification — proof requests with position dropdown</label>${chanSel('ch_verification', staffChannels, t.channels.verification)}</div>
<div><label>📣 Staff announcements — new staff, promotions, farewells</label>${chanSel('ch_announcements', staffChannels, t.channels.announcements)}</div>
<div><label>📖 Guide — new staff member is pinged here with the guide</label>${chanSel('ch_guide', staffChannels, t.channels.guide)}</div>
<div><label>📌 Roster — one live message, auto-updated</label>${chanSel('ch_roster', staffChannels, t.channels.roster)}</div>
<div><label>⚠️ Strikes log</label>${chanSel('ch_strikes', staffChannels, t.channels.strikes)}</div>
<div><label>🌴 Breaks — requests with Approve / Deny</label>${chanSel('ch_breaks', staffChannels, t.channels.breaks)}</div>
<div><label>🗒️ General staff log (fallback)</label>${chanSel('ch_log', staffChannels, t.channels.log)}</div>
<div><label>📊 Weekly report</label>${chanSel('ch_reports', staffChannels, t.channels.reports)}</div>
<div><label>Main server: public "welcome our new staff" post</label>${chanSel('ch_mainAnnouncements', mainChannels, t.channels.mainAnnouncements)}</div></div></div>
<h2>Roles</h2><div class="card"><label>Manager roles (staff server) — can verify, promote, strike, approve breaks. Administrators always can.</label>${multi('managerRoles', staffRoles, t.managerRoles)}
<div class="row"><div><label>"Staff" role — main server (given to every verified member)</label>${roleSel('r_staffMain', mainRoles, t.roles.staffMain)}</div><div><label>"Staff" role — staff server</label>${roleSel('r_staffStaff', staffRoles, t.roles.staffStaff)}</div><div><label>LOA role — main server</label>${roleSel('r_loaMain', mainRoles, t.roles.loaMain)}</div><div><label>LOA role — staff server</label>${roleSel('r_loaStaff', staffRoles, t.roles.loaStaff)}</div></div><label>Pending role — staff server (accepted applicants who are not verified yet)</label>${roleSel('r_pendingStaff', staffRoles, t.roles.pendingStaff)}
<label>Interview managers — main server role that can see interview channels (the manager who opens it always can)</label>${roleSel('r_managerMain', mainRoles, t.roles.managerMain)}</div>
<h2>Interviews &amp; activity</h2><div class="card"><label>Category in the main server for interview channels</label>${sel('interviewCategory', mainCategories, t.interviewCategory, '— top level —')}
<label>Count messages only in these staff-server channels (empty = all)</label>${multi('statsChannels', staffChannels, t.statsChannels, (c) => `# ${c.name}`)}
<div class="row3"><div>${check('reportEnabled', t.report.enabled, 'Weekly report')}</div><div><label>Day</label><select name="reportDay">${['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'].map((d, i) => `<option value="${i}" ${t.report.day === i ? 'selected' : ''}>${d}</option>`).join('')}</select></div><div><label>Hour (UTC)</label><input type="number" name="reportHour" min="0" max="23" value="${t.report.hour}"></div></div>
<label>Flag staff as inactive after (days without activity)</label><input type="number" name="inactiveDays" min="1" max="90" value="${t.report.inactiveDays}"></div>
<h2>Behaviour</h2><div class="card"><label>Nickname format — placeholders <code>{position}</code> (the position's nickname tag) <code>{name}</code> <code>{department}</code> (max 32 chars), e.g. <code>{position} | {name}</code> → <code>Mod | Ishan</code></label><input type="text" name="nicknameFormat" value="${esc(t.nicknameFormat)}" maxlength="32" required>
${check('requireApplication', t.requireApplication, 'Require an accepted application before /verify', 'Turn off to verify anyone directly')}
<div class="row3"><div><label>Strike limit</label><input type="number" name="strikeLimit" min="1" max="20" value="${t.strikeLimit}"></div><div><label>Strikes expire after (days, 0 = never)</label><input type="number" name="strikeExpiryDays" min="0" max="365" value="${t.strikeExpiryDays}"></div><div><label>When the limit is reached</label><select name="strikeAction"><option value="alert" ${t.strikeAction === 'alert' ? 'selected' : ''}>Alert managers only</option><option value="demote" ${t.strikeAction === 'demote' ? 'selected' : ''}>Demote one level</option><option value="remove" ${t.strikeAction === 'remove' ? 'selected' : ''}>Remove from staff</option></select></div></div></div>
<button>Save settings</button></form>
<h2>Messages</h2><form method="post"><div class="card">${csrf(session)}<input type="hidden" name="action" value="messages"><p class="sub" style="margin:0">Placeholders: <code>{user}</code> mention · <code>{name}</code> · <code>{position}</code> · <code>{department}</code> · <code>{nickname}</code> · <code>{channels}</code> · <code>{server}</code> · <code>{staffserver}</code> · <code>{invite}</code> (accept DM) · <code>{reason}</code> (deny DM). Markdown works.</p>
<div class="row msgs"><div><label>📖 Guide post (guide channel, pings the new staff member)</label><textarea name="msg_guide" style="min-height:220px">${esc(t.messages.guide)}</textarea></div><div><label>📣 Announcement text (staff announcements)</label><textarea name="msg_announcement">${esc(t.messages.announcement)}</textarea><label>✅ Verified DM</label><textarea name="msg_verifyDm">${esc(t.messages.verifyDm)}</textarea></div><div><label>🎉 Application accepted DM</label><textarea name="msg_acceptDm" style="min-height:140px">${esc(t.messages.acceptDm)}</textarea></div><div><label>❌ Application denied DM</label><textarea name="msg_denyDm" style="min-height:140px">${esc(t.messages.denyDm)}</textarea></div></div>
<button class="sec" style="margin-top:12px">Save messages</button></div></form>
<h2>Danger zone</h2><div class="card"><p class="sub">Unlinking deletes departments, roster, applications and strikes for this pair. Roles in Discord are not touched.</p>${btnForm(session, 'unlink', 'Unlink servers', 'danger', '', 'Really unlink and delete all StaffHub data for this pair?')}</div>` }),
};
